name: Release
permissions:
  contents: write

on:
  release:
    types: [created]

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup dotnet
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: "8.x"
      - name: Display dotnet version
        run: dotnet --version
      - name: Compile
        run: make VERSION="${TAG_NAME#v}"
        env:
          TAG_NAME: ${{ github.event.release.tag_name }}
      - name: Zip extension
        run: |
          mkdir -p MxLintExtension
          cp -r bin/Debug/net8.0/* MxLintExtension
          zip -r "MxLintExtension-${{ github.event.release.tag_name }}.zip" MxLintExtension
      - name: Upload release asset
        uses: softprops/action-gh-release@v2
        with:
          files: MxLintExtension-${{ github.event.release.tag_name }}.zip


